export const primitives = {
  public: [
    { id: 'accessible-icon', name: 'Accessible Icon' },
    { id: 'accordion', name: 'Accordion' },
    { id: 'alert-dialog', name: 'Alert Dialog' },
    { id: 'aspect-ratio', name: 'Aspect Ratio' },
    { id: 'avatar', name: 'Avatar' },
    { id: 'checkbox', name: 'Checkbox' },
    { id: 'collapsible', name: 'Collapsible' },
    { id: 'context-menu', name: 'Context Menu' },
    { id: 'dialog', name: 'Dialog' },
    { id: 'direction', name: 'Direction Provider' },
    { id: 'dropdown-menu', name: 'Dropdown Menu' },
    { id: 'form', name: 'Form' },
    { id: 'hover-card', name: 'Hover Card' },
    { id: 'label', name: 'Label' },
    { id: 'menubar', name: 'Menubar' },
    { id: 'navigation-menu', name: 'Navigation Menu' },
    { id: 'one-time-password-field', name: 'One-Time Password Field' },
    { id: 'password-toggle-field', name: 'Password Toggle Field' },
    { id: 'popover', name: 'Popover' },
    { id: 'portal', name: 'Portal' },
    { id: 'progress', name: 'Progress' },
    { id: 'radio-group', name: 'Radio Group' },
    { id: 'scroll-area', name: 'Scroll Area' },
    { id: 'select', name: 'Select' },
    { id: 'separator', name: 'Separator' },
    { id: 'slider', name: 'Slider' },
    { id: 'slot', name: 'Slot' },
    { id: 'switch', name: 'Switch' },
    { id: 'tabs', name: 'Tabs' },
    { id: 'toast', name: 'Toast' },
    { id: 'toggle', name: 'Toggle' },
    { id: 'toggle-group', name: 'Toggle Group' },
    { id: 'toolbar', name: 'Toolbar' },
    { id: 'tooltip', name: 'Tooltip' },
    { id: 'visually-hidden', name: 'Visually Hidden' },
  ] as const,
  internal: [
    //
    { id: 'arrow', name: 'Arrow' },
    { id: 'collection', name: 'Collection' },
    { id: 'dismissable-layer', name: 'Dismissable Layer' },
    { id: 'focus-guards', name: 'Focus Guards' },
    { id: 'focus-scope', name: 'Focus Scope' },
    { id: 'menu', name: 'Menu' },
    { id: 'popper', name: 'Popper' },
    { id: 'roving-focus', name: 'Roving Focus' },
  ],
} as const;
