import type * as React from 'react';
import type { Metadata } from 'next';
import { primitives } from '@repo/test-registry';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <h1>Next.js testing</h1>
        <div style={{ display: 'flex', gap: '10em' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5em' }}>
            <h2>Public APIs</h2>
            {primitives.public.map((primitive) => (
              <Link key={primitive.id} href={`/${primitive.id}`}>
                {primitive.name}
              </Link>
            ))}
            <hr />
            <h2>Internal APIs</h2>
            {primitives.internal.map((primitive) => (
              <Link key={primitive.id} href={`/${primitive.id}`}>
                {primitive.name}
              </Link>
            ))}
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
