import * as React from 'react';
import { Label, styles, useLabelContext } from './Label';

export default { title: 'Label' };

export const Basic = () => <Label style={styles.root}>Label</Label>;
export const InlineStyle = () => <Label as={Root}>Label</Label>;

export const AutoGeneratedId = () => (
  <Label as={Root}>
    Label <Control />
  </Label>
);

export const SuppliedId = () => (
  <Label id="test" as={Root}>
    Label <Control />
  </Label>
);

/* -------------------------------------------------------------------------------------------------
 * Control
 * -----------------------------------------------------------------------------------------------*/

const Control = () => {
  const id = useLabelContext();
  return <span>{id}</span>;
};

/* -------------------------------------------------------------------------------------------------
 * Styled components
 * -----------------------------------------------------------------------------------------------*/

const Root = React.forwardRef<HTMLLabelElement, React.ComponentProps<typeof Label>>(
  ({ children, ...props }, forwardedRef) => (
    <label
      {...props}
      style={{ ...styles.root, border: '1px solid gainsboro', margin: 10, padding: 10 }}
      ref={forwardedRef}
    >
      {children}
    </label>
  )
);
